spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId:
            clientSecret:
            scope:
              - email
              - public_profile
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile
